version: '3'
services:
  webapi:
    build: .
    container_name: go-webapi
    ports: 
      - 5000:5000
    depends_on: 
      - mysql
    restart: always

  mysql:
    image: mysql
    container_name: ${DB_CONTAINER_NAME}
    expose:
      - 3306  
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data:


